// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFHkw3vWsdn816Ucv46lfvDIUvKp9kpto',
    appId: '1:659474133610:web:b0f515984e9a0697195013',
    messagingSenderId: '659474133610',
    projectId: 'bumduz-pharmacy',
    authDomain: 'bumduz-pharmacy.firebaseapp.com',
    storageBucket: 'bumduz-pharmacy.firebasestorage.app',
    measurementId: 'G-Z1BPT9M321',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbHL7MRaxIqJuiCgzzfCxzEIXAuNv7yNI',
    appId: '1:659474133610:android:bffc97678fa40853195013',
    messagingSenderId: '659474133610',
    projectId: 'bumduz-pharmacy',
    storageBucket: 'bumduz-pharmacy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgSZr2C6T5K-D7s-ZfS3hjwCU1PhLNe7Q',
    appId: '1:659474133610:ios:58d950886e030db2195013',
    messagingSenderId: '659474133610',
    projectId: 'bumduz-pharmacy',
    storageBucket: 'bumduz-pharmacy.firebasestorage.app',
    iosBundleId: 'eng.bumduz.pharmacy',
  );
}
